"""wiki_search_index — index knowledge-wiki bodies for retrieval (ADR 012 Phase 3b).

On each `knowledge_article_created` / `_revised` event it reads the article's
*current* body (not the event's snapshot — so a replayed old event still
indexes the current page), heading-aware-chunks it, embeds the chunks via
mcp-embedder (BGE-M3, 1024-dim, same as document_chunks), and in one
transaction DELETEs the article's old `wiki_chunks` rows and INSERTs the fresh
ones. So `wiki_chunks` always holds exactly the current revision's chunks and
`search_knowledge` (Phase 3c) can query it without a revision filter.

On `knowledge_article_archived` it DELETEs the article's chunks (drops the page
from the search index).

A stub page (`body_md = ''`, dirty, not yet regenerated by wiki_regen) produces
zero chunks — the DELETE+INSERT is a clean no-op until the body is filled and a
`_revised` event fires.

Error policy (mirrors chunk_embedder):
  * mcp-embedder 4xx → permanent: log + skip (ack), leave the old chunks in
    place (stale beats empty).
  * mcp-embedder 5xx / network → transient: propagate (no ack → retry).

Connects as chemclaw_service (BYPASSRLS).
"""

from __future__ import annotations

import asyncio
import logging
import re
from typing import Any

import httpx
import psycopg
from psycopg.rows import dict_row
from pydantic_settings import SettingsConfigDict

from services.mcp_tools.common.logging import configure_logging
from services.projectors.common.base import BaseProjector, ProjectorSettings

log = logging.getLogger("projector.wiki_search_index")

# Roughly 1.4 KB per chunk — LLM-generated wiki pages run a few KB, so a page
# becomes a handful of chunks. Mid-section flushes happen at this size; we
# don't sub-split paragraphs (a single huge section becomes one big chunk —
# acceptable for v1).
_TARGET_CHARS = 1400
# Stay well under mcp-embedder's input cap.
_EMBED_BATCH = 32
_HEADING_RE = re.compile(r"^(#{1,6})\s+(\S.*)$")


class Settings(ProjectorSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")
    mcp_embedder_url: str = "http://localhost:8004"


class _BadEmbedError(Exception):
    """Permanent embedder error — the article is acked without re-indexing."""


def _chunk_markdown(body: str, *, target_chars: int = _TARGET_CHARS) -> list[tuple[str | None, str]]:
    """Heading-aware chunk a Markdown body into [(heading_path, text), …].

    Walks lines, tracking the ATX-heading stack; flushes a chunk when it hits a
    new heading or the buffer exceeds `target_chars`. The heading line stays at
    the top of its section's first chunk; `heading_path` is recorded separately
    for every chunk regardless.
    """
    stack: list[tuple[int, str]] = []  # (level, text)
    chunks: list[tuple[str | None, str]] = []
    buf: list[str] = []

    def heading_path() -> str | None:
        return " > ".join(t for _l, t in stack) or None

    def flush() -> None:
        nonlocal buf
        text = "\n".join(buf).strip()
        if text:
            chunks.append((heading_path(), text))
        buf = []

    for ln in body.splitlines():
        m = _HEADING_RE.match(ln)
        if m:
            flush()
            lvl, txt = len(m.group(1)), m.group(2).strip()
            while stack and stack[-1][0] >= lvl:
                stack.pop()
            stack.append((lvl, txt))
            buf = [ln]  # keep the heading at the top of this section's chunk
        else:
            buf.append(ln)
            if sum(len(x) + 1 for x in buf) > target_chars:
                flush()
    flush()
    return chunks


class WikiSearchIndexProjector(BaseProjector):
    name = "wiki_search_index"
    interested_event_types = (
        "knowledge_article_created",
        "knowledge_article_revised",
        "knowledge_article_archived",
    )

    def __init__(self, settings: Settings) -> None:
        super().__init__(settings)
        self._s: Settings = settings
        self._client = httpx.AsyncClient(timeout=60.0)

    async def aclose(self) -> None:
        await self._client.aclose()

    async def handle(
        self,
        *,
        event_id: str,
        event_type: str,
        source_table: str | None,  # noqa: ARG002
        source_row_id: str | None,
        payload: dict[str, Any],
    ) -> None:
        article_id = payload.get("article_id") or source_row_id
        if not article_id:
            log.warning("event %s: missing article_id; acking", event_id)
            return

        async with await psycopg.AsyncConnection.connect(self._s.postgres_dsn, row_factory=dict_row) as conn:
            if event_type == "knowledge_article_archived":
                async with conn.cursor() as cur:
                    await cur.execute("DELETE FROM wiki_chunks WHERE article_id = %s::uuid", (article_id,))
                    n = cur.rowcount
                await conn.commit()
                log.info("event %s: archived article %s → dropped %d chunk(s) from search index", event_id, article_id, n)
                return

            async with conn.cursor() as cur:
                await cur.execute(
                    "SELECT slug, revision, body_md, status FROM knowledge_articles WHERE id = %s::uuid",
                    (article_id,),
                )
                row = await cur.fetchone()
            if not row:
                log.warning("event %s: knowledge_articles row %s gone; acking", event_id, article_id)
                return
            if row["status"] != "current":
                # Archived between the event and now — drop its chunks.
                async with conn.cursor() as cur:
                    await cur.execute("DELETE FROM wiki_chunks WHERE article_id = %s::uuid", (article_id,))
                await conn.commit()
                return

            slug, revision, body = row["slug"], int(row["revision"]), row["body_md"] or ""
            pieces = _chunk_markdown(body)

            vectors: list[list[float] | None]
            if pieces:
                try:
                    vectors = await self._embed([p[1] for p in pieces])
                except _BadEmbedError as exc:
                    log.warning("event %s: embedder permanent error for %s: %s — leaving old chunks", event_id, slug, exc)
                    return  # ack; don't touch wiki_chunks (stale > empty)
            else:
                vectors = []

            # DELETE-then-INSERT in one transaction: the article's chunks are
            # always exactly the current revision's.
            async with conn.cursor() as cur:
                await cur.execute("DELETE FROM wiki_chunks WHERE article_id = %s::uuid", (article_id,))
                for idx, ((hp, text), vec) in enumerate(zip(pieces, vectors, strict=True)):
                    literal = "[" + ",".join(f"{v:.8f}" for v in vec) + "]" if vec is not None else None
                    await cur.execute(
                        """
                        INSERT INTO wiki_chunks
                          (article_id, slug, revision, chunk_index, heading_path, text, embedding, token_count)
                        VALUES (%s::uuid, %s, %s, %s, %s, %s, %s::vector, %s)
                        """,
                        (article_id, slug, revision, idx, hp, text, literal, max(1, len(text) // 4)),
                    )
            await conn.commit()
            log.info("event %s: indexed %s rev %d → %d chunk(s)", event_id, slug, revision, len(pieces))

    async def _embed(self, inputs: list[str]) -> list[list[float] | None]:
        out: list[list[float] | None] = []
        for start in range(0, len(inputs), _EMBED_BATCH):
            batch = inputs[start : start + _EMBED_BATCH]
            try:
                r = await self._client.post(
                    f"{self._s.mcp_embedder_url}/tools/embed_text",
                    json={"inputs": batch, "normalize": True},
                )
            except httpx.HTTPError:
                raise  # transient — propagate for retry
            if 400 <= r.status_code < 500:
                raise _BadEmbedError(f"embedder 4xx: {r.status_code} {r.text[:200]}")
            r.raise_for_status()
            vectors = r.json().get("vectors")
            if not isinstance(vectors, list) or len(vectors) != len(batch):
                raise _BadEmbedError("embedder returned a malformed/short vectors array")
            out.extend(vectors)
        return out


async def amain() -> None:  # pragma: no cover — process entrypoint
    settings = Settings()
    configure_logging(settings.projector_log_level, service="wiki_search_index")
    proj = WikiSearchIndexProjector(settings)
    try:
        await proj.run()
    finally:
        await proj.aclose()


def main() -> None:  # pragma: no cover
    asyncio.run(amain())


if __name__ == "__main__":
    main()
