-- Mock ELN — seed data loader.
-- Auto-generated by services/mock_eln/seed/generator.py.
-- DO NOT EDIT BY HAND. Re-run the generator instead.
--
-- Gating: this loader only runs when the postgres GUC
--   app.mock_eln_enabled = 'on'
-- is set on the session or the database.
--
-- Apply with:
--   psql -v ON_ERROR_STOP=1 \
--     -c "SET app.mock_eln_enabled = 'on';" \
--     -f db/seed/20_mock_eln_data.sql
-- or set it persistently:
--   ALTER DATABASE chemclaw SET app.mock_eln_enabled = 'on';
--
-- Re-running is safe: the gated block TRUNCATEs the mock_eln tables
-- (CASCADE) before \copying so the resulting state is byte-identical
-- to a fresh run with the same fixtures.

\set ON_ERROR_STOP on

-- Resolve the gate into a psql boolean variable. \if accepts only
-- a literal boolean, so we compute the comparison server-side and
-- \gset the resulting true/false into :mock_eln_enabled.
SELECT (coalesce(current_setting('app.mock_eln_enabled', true), 'off') = 'on')
       AS mock_eln_enabled \gset

\if :mock_eln_enabled
BEGIN;

TRUNCATE TABLE mock_eln.audit_trail, mock_eln.results, mock_eln.samples,
               mock_eln.entry_attachments, mock_eln.entries,
               mock_eln.reactions, mock_eln.compounds, mock_eln.methods,
               mock_eln.notebooks, mock_eln.projects RESTART IDENTITY CASCADE;

\copy mock_eln.projects (id, code, name, therapeutic_area, started_at, ended_at, pi_email, metadata, created_at, updated_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/projects.copy.gz' WITH (FORMAT csv, NULL '');
\copy mock_eln.notebooks (id, project_id, name, kind, metadata, created_at, updated_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/notebooks.copy.gz' WITH (FORMAT csv, NULL '');
\copy mock_eln.methods (id, code, name, instrument_kind, description, parameters, created_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/methods.copy.gz' WITH (FORMAT csv, NULL '');
\copy mock_eln.compounds (id, smiles_canonical, inchikey, mw, external_id, project_id, metadata, created_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/compounds.copy.gz' WITH (FORMAT csv, NULL '');
\copy mock_eln.reactions (id, canonical_smiles_rxn, family, step_number, project_id, metadata, created_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/reactions.copy.gz' WITH (FORMAT csv, NULL '');
\copy mock_eln.entries (id, notebook_id, project_id, reaction_id, schema_kind, title, author_email, signed_by, status, entry_shape, data_quality_tier, fields_jsonb, freetext, freetext_length_chars, created_at, modified_at, signed_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/entries.copy.gz' WITH (FORMAT csv, NULL '');
\copy mock_eln.entry_attachments (id, entry_id, filename, mime_type, size_bytes, description, uri, created_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/entry_attachments.copy.gz' WITH (FORMAT csv, NULL '');
\copy mock_eln.samples (id, entry_id, sample_code, compound_id, amount_mg, purity_pct, notes, created_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/samples.copy.gz' WITH (FORMAT csv, NULL '');
\copy mock_eln.results (id, sample_id, method_id, metric, value_num, value_text, unit, measured_at, metadata, created_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/results.copy.gz' WITH (FORMAT csv, NULL '');
\copy mock_eln.audit_trail (id, entry_id, actor_email, action, field_path, old_value, new_value, reason, occurred_at) FROM PROGRAM 'gunzip -c test-fixtures/mock_eln/world-default/audit_trail.copy.gz' WITH (FORMAT csv, NULL '');

COMMIT;

\echo 'Mock ELN seed data loaded.'
\else
\echo 'Mock ELN seed skipped — set app.mock_eln_enabled = ''on'' to load.'
\endif
