// Request-scoped context propagated via AsyncLocalStorage.
//
// Why ALS instead of threading explicit args: the userEntraId needs to reach
// every outbound MCP call so the JWT can be minted with the right `user`
// claim. Threading it through 21 builtin tool factories + the harness +
// every postJson/getJson site is 30+ edits and a maintenance burden every
// time a new tool ships. ALS makes propagation automatic — the harness
// sets it once per turn, postJson reads it transparently.
//
// Tradeoff: ALS context can be lost if a tool spawns a non-awaited promise
// (.catch() detachment, fire-and-forget setTimeouts). For our codebase that's
// not a concern — every async boundary is awaited.
//
// Test-friendly: `getRequestContext()` returns undefined outside an ALS run,
// which makes postJson behave as if no auth is configured (matches dev mode).

import { AsyncLocalStorage } from "node:async_hooks";

/**
 * Per-request retry budget shared across all `withRetry` call sites within
 * the same AsyncLocalStorage context. Prevents a fan-out chain of N tools
 * each retrying M times from amplifying into N×M attempts against an
 * already-saturated downstream service.
 *
 * The budget is mutable (decremented in place) so every `withRetry` call
 * in the same request sees the running total without needing to thread a
 * return value through the call stack.
 */
export interface RetryBudget {
  remaining: number;
}

export interface RequestContext {
  /** Entra-ID of the calling user — flows into JWT `user` claim. */
  userEntraId: string;
  /** Active session id (if any) — useful for log correlation. */
  sessionId?: string;
  /**
   * Per-request correlation id. Generated by the Fastify pre-handler in
   * `index.ts` (or extracted from an inbound `X-Request-Id` header) and
   * threaded through every outbound MCP call so Python services bind the
   * same id into their log records. The Pino mixin in
   * `observability/log-context.ts` copies it onto every log entry within
   * the request scope. Optional because background tasks (reanimator,
   * optimizer) run outside any HTTP request — they synthesize their own
   * id when needed.
   */
  requestId?: string;
  /**
   * Pre-computed sha256 hash of `userEntraId` (16 hex chars). Filled
   * once at the route wrapper so the Pino mixin doesn't recompute it
   * on every log emission — a per-turn agent loop can emit dozens of
   * log lines, and per-call sha256 was wasted CPU. The hash function
   * is the same as `observability/user-hash.ts:hashUser` so the value
   * is exactly what would have been produced inline.
   */
  userHash?: string;
  /**
   * Upstream AbortSignal threaded through from the route's FastifyRequest.
   * postJson / getJson in `mcp/postJson.ts` read this to cancel in-flight
   * MCP calls when the originating client disconnects mid-stream. Optional
   * — background tasks (reanimator, optimizer) and tests run without an
   * upstream signal and the helpers fall back to their own per-call timeout
   * AbortController as before.
   */
  signal?: AbortSignal;
  /**
   * Per-request retry budget shared across every `withRetry` invocation
   * within this AsyncLocalStorage context. When set, `withRetry` decrements
   * this before each retry attempt and skips further retries once exhausted,
   * bounding the total amplification from fan-out tool chains.
   *
   * Default: undefined (no per-request cap; per-call defaults apply).
   * Production routes set this via `PER_REQUEST_RETRY_BUDGET_DEFAULT`.
   */
  retryBudget?: RetryBudget;
}

const _storage = new AsyncLocalStorage<RequestContext>();

/**
 * Read the current request context. Returns undefined when called outside
 * `runWithRequestContext` — that's the test/standalone path.
 */
export function getRequestContext(): RequestContext | undefined {
  return _storage.getStore();
}

/**
 * Run `fn` inside a request context. The context is available to every
 * async function awaited from within `fn` (via Node's async-hooks).
 */
export function runWithRequestContext<T>(
  ctx: RequestContext,
  fn: () => Promise<T>,
): Promise<T> {
  return _storage.run(ctx, fn);
}
