"""Streamlit Optimizer page — Phase E.

Tabs:
  GEPA Runs        — nightly GEPA run history; per-prompt candidate diffs + lift.
  Skill Promotion  — promotion / demotion event log.
  Shadow Scoring   — side-by-side score curves per shadow prompt.
  Golden-Set Scores — latest pass-rate per class + trend sparkline.

Reads from the agent-claw optimizer API endpoints:
  GET /api/optimizer/runs
  GET /api/optimizer/promotions
  GET /api/optimizer/shadow
  GET /api/optimizer/golden
"""

from __future__ import annotations

import logging
from typing import Any

import requests
import streamlit as st

try:
    from services.frontend.settings import get_settings
except ImportError:
    # Running standalone — provide a fallback.
    class _FallbackSettings:
        agent_base_url = "http://localhost:3101"

    def get_settings():
        return _FallbackSettings()


_log = logging.getLogger(__name__)

st.set_page_config(page_title="ChemClaw — Optimizer", page_icon="⚙️", layout="wide")

settings = get_settings()
AGENT_URL = settings.agent_base_url.rstrip("/")

user_entra_id = st.query_params.get("user_id", "dev@example.com")


# ---------------------------------------------------------------------------
# API helpers
# ---------------------------------------------------------------------------

def _headers() -> dict[str, str]:
    return {"x-user-id": user_entra_id, "Content-Type": "application/json"}


def _fetch(endpoint: str) -> dict[str, Any] | None:
    """GET an optimizer endpoint; return parsed JSON or None on error."""
    try:
        resp = requests.get(
            f"{AGENT_URL}/api/optimizer/{endpoint}",
            headers=_headers(),
            timeout=10,
        )
        resp.raise_for_status()
        return resp.json()
    except Exception as exc:
        st.error(f"Failed to load {endpoint}: {exc}")
        return None


# ---------------------------------------------------------------------------
# Page
# ---------------------------------------------------------------------------

st.title("ChemClaw Optimizer")
st.caption("Nightly GEPA self-improvement loop — Phase E")

tab_gepa, tab_promotion, tab_shadow, tab_golden = st.tabs(
    ["GEPA Runs", "Skill Promotion Log", "Shadow Comparisons", "Golden-Set Scores"]
)

# ---------------------------------------------------------------------------
# Tab 1 — GEPA Runs
# ---------------------------------------------------------------------------

with tab_gepa:
    st.subheader("Nightly GEPA candidate history")
    st.caption(
        "Each row is a candidate prompt generated by the DSPy GEPA optimizer. "
        "Candidates start as inactive (shadow) and are auto-promoted after 7 days if criteria are met."
    )

    data = _fetch("runs")
    if data is None:
        st.info("Optimizer API unavailable. Is the agent-claw service running?")
    else:
        runs = data.get("runs", [])
        if not runs:
            st.info("No GEPA runs yet. The nightly job runs at 02:00 UTC.")
        else:
            for run in runs:
                metadata = run.get("gepa_metadata") or {}
                with st.expander(
                    f"**{run['name']}** v{run['version']} — "
                    f"golden={metadata.get('golden_score', 'n/a'):.2%} "
                    f"feedback={metadata.get('feedback_rate', 'n/a'):.2%} "
                    f"{'✅ active' if run.get('active') else '🕐 shadow' if run.get('shadow_until') else '⏸ inactive'}",
                    expanded=False,
                ):
                    col1, col2 = st.columns(2)
                    with col1:
                        st.metric("Golden score", f"{metadata.get('golden_score', 0):.1%}")
                        st.metric("Feedback rate", f"{metadata.get('feedback_rate', 0):.1%}")
                        st.metric("Training examples", metadata.get("training_examples", "—"))
                    with col2:
                        st.metric("GEPA generations", metadata.get("generations", "—"))
                        st.metric("Population size", metadata.get("population_size", "—"))
                        shadow_until = run.get("shadow_until")
                        if shadow_until:
                            st.metric("Shadow until", shadow_until[:10])

                    classes = metadata.get("per_class_breakdown") or {}
                    if classes:
                        st.markdown("**Per-class example counts:**")
                        class_cols = st.columns(len(classes))
                        for i, (cls, count) in enumerate(classes.items()):
                            with class_cols[i]:
                                st.metric(cls, count)

                    classes_met = metadata.get("classes_met_minimum") or []
                    if classes_met:
                        st.success(f"Classes met minimum (≥30 examples): {', '.join(classes_met)}")


# ---------------------------------------------------------------------------
# Tab 2 — Skill Promotion Log
# ---------------------------------------------------------------------------

with tab_promotion:
    st.subheader("Skill promotion / demotion events")
    st.caption(
        "Promotion: success_count/total_runs ≥ 0.55 AND total_runs ≥ 30. "
        "Demotion: rate < 0.40 over the last 30 runs."
    )

    data = _fetch("promotions")
    if data is None:
        st.info("Optimizer API unavailable.")
    else:
        events = data.get("events", [])
        if not events:
            st.info("No promotion/demotion events yet.")
        else:
            EVENT_ICONS = {
                "promote": "✅",
                "demote": "⬇️",
                "shadow_start": "🔵",
                "shadow_promote": "✅",
                "shadow_reject": "❌",
            }
            for ev in events:
                icon = EVENT_ICONS.get(ev["event_type"], "•")
                st.markdown(
                    f"{icon} **{ev['skill_name']}** v{ev['version']} — "
                    f"`{ev['event_type']}` — {ev.get('reason', '')} "
                    f"— *{str(ev.get('created_at', ''))[:16]}*"
                )


# ---------------------------------------------------------------------------
# Tab 3 — Shadow Comparisons
# ---------------------------------------------------------------------------

with tab_shadow:
    st.subheader("Shadow prompt score curves")
    st.caption(
        "Shadow prompts run in parallel on a sampled fraction of traffic "
        f"(AGENT_SHADOW_SAMPLE, default 10%). "
        "Auto-promoted after 7 days if shadow score ≥ active + 0.05, "
        "absolute floor 0.80, no per-class drop > 2pp."
    )

    data = _fetch("shadow")
    if data is None:
        st.info("Optimizer API unavailable.")
    else:
        shadows = data.get("shadows", [])
        if not shadows:
            st.info("No shadow runs recorded yet.")
        else:
            for s in shadows:
                with st.expander(
                    f"**{s['prompt_name']}** v{s['version']} — "
                    f"mean={float(s.get('mean_score', 0)):.2%} — "
                    f"{s.get('run_count', 0)} runs"
                ):
                    col1, col2, col3 = st.columns(3)
                    with col1:
                        st.metric("Mean score", f"{float(s.get('mean_score', 0)):.1%}")
                    with col2:
                        st.metric("Total runs", s.get("run_count", "—"))
                    with col3:
                        last = str(s.get("last_run_at") or "—")[:16]
                        st.metric("Last run", last)


# ---------------------------------------------------------------------------
# Tab 4 — Golden-Set Scores
# ---------------------------------------------------------------------------

with tab_golden:
    st.subheader("Golden-set pass-rate trend")
    st.caption(
        "Latest shadow_run_scores used as a proxy for golden-set scoring. "
        "Run `/eval golden` in chat for the held-out fixture evaluation."
    )

    data = _fetch("golden")
    if data is None:
        st.info("Optimizer API unavailable.")
    else:
        scores = data.get("scores", [])
        if not scores:
            st.info("No golden-set scores recorded yet.")
        else:
            # Group by prompt_name for sparklines.
            from collections import defaultdict
            grouped: dict[str, list[float]] = defaultdict(list)
            for s in scores:
                grouped[s["prompt_name"]].append(float(s.get("score", 0)))

            for pname, vals in grouped.items():
                col1, col2 = st.columns([1, 3])
                with col1:
                    mean_score = sum(vals) / len(vals)
                    st.metric(pname, f"{mean_score:.1%}", delta=None)
                with col2:
                    # Simple text sparkline.
                    sparkline = "".join("▁▂▃▄▅▆▇█"[min(7, int(v * 8))] for v in vals[-20:])
                    st.code(sparkline, language=None)
